// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sykovmsofsgjcuxuhors.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5a292bXNvZnNnamN1eHVob3JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NTQ5NzYsImV4cCI6MjA3MTAzMDk3Nn0.9Q55a-Ib0ksbjOuMRrydKptSrVcfYe5J9uOGD6X9MFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});